

create table public.users (
    id uuid primary key default gen_random_uuid(),
    email text unique not null,
    password text not null,
    name text not null,
    photo text
);

create table public.rooms (
    id bigint generated by default as identity primary key,
    slug text unique not null,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    admin_id uuid not null,
    constraint fk_admin foreign key(admin_id) references public.users(id)
);

create table public.chats (
    id bigint generated by default as identity primary key,
    room_id bigint not null,
    message text not null,
    user_id uuid not null,
    constraint fk_room foreign key(room_id) references public.rooms(id),
    constraint fk_user foreign key(user_id) references public.users(id)
);

comment on table public.users is 'Stores user account information.';
comment on table public.rooms is 'Represents a chat or drawing room.';
comment on table public.chats is 'Stores individual chat messages.';